export const LOADING = 'LOADING';
export type LOADING = typeof LOADING;

export const LOGIN_USER = 'LOGIN_USER';
export type LOGIN_USER = typeof LOGIN_USER;

export const USER_MESSAGE = 'USER_MESSAGE';
export type USER_MESSAGE = typeof USER_MESSAGE;

export const RESET_CONNECTION = 'RESET_CONNECTION';
export type RESET_CONNECTION = typeof RESET_CONNECTION;

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export type CLEAR_MESSAGE = typeof CLEAR_MESSAGE;

export const SAVE_CONVERSATIONS = 'SAVE_CONVERSATIONS';
export type SAVE_CONVERSATIONS = typeof SAVE_CONVERSATIONS;

export const SAVE_DETAILS = 'SAVE_DETAILS';
export type SAVE_DETAILS = typeof SAVE_DETAILS;

export const LOGOUT = 'LOGOUT';
export type LOGOUT = typeof LOGOUT;

export const USER_RESULTS = 'USER_RESULTS';
export type USER_RESULTS = typeof USER_RESULTS;

export const CLEAR_USER_RESULTS = 'CLEAR_USER_RESULTS';
export type CLEAR_USER_RESULTS = typeof CLEAR_USER_RESULTS;

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export type ADD_NOTIFICATION = typeof ADD_NOTIFICATION;

export const FRIENDS_RESULT = 'FRIENDS_RESULT';
export type FRIENDS_RESULT = typeof FRIENDS_RESULT;

export const ADD_CONVERSATION = 'ADD_CONVERSATION';
export type ADD_CONVERSATION = typeof ADD_CONVERSATION;

export const SAVE_SELECTION = 'SAVE_SELECTION';
export type SAVE_SELECTION = typeof SAVE_SELECTION;

export const ADD_MESSAGE = 'ADD_MESSAGE';
export type ADD_MESSAGE = typeof ADD_MESSAGE;

export const LEFT_CONVERSATION = 'LEFT_CONVERSATION';
export type LEFT_CONVERSATION = typeof LEFT_CONVERSATION;